### ISSUE TITLE
under swift2.0 has errors

### ISSUE THREAD

**Issue by lacklock** [thii/SwiftColors#16]
under swift2.0 has errors

**Comment by yasiraliraj** [comment]
any updates for swift 2.0?

**Comment by sunkanmi-akintoye** [comment]
@yasiraliraj @lacklock  advance() method has been changed to advancedBy().

I have submitted a pull request in Swift 2.0 branch, in the meantime you can make use of this code.

https://github.com/sunkanmi-akintoye/SwiftColors/blob/master/SwiftColors/SwiftColors.swift

**Comment by agquick** [comment]
+1 can someone merge the fix and update the cocoapod?

**Comment by Gumarelo** [comment]
+1

**Comment by thii** [comment]
Just updated the CocoaPods version. You don't need to wait for the CocoaPods version anyway, you can always use the latest version by adding the following to your Podfile. 
`pod 'SwiftColors', :git => 'https://github.com/thii/SwiftColors.git'`
