### ISSUE TITLE
Using a default value for alpha

### ISSUE THREAD

**Issue by NorthernRealities** [thii/SwiftColors#4]
Hi,

I've built a library of pre-defined colours and am looking at adding some more helper functions.  But in my  code for each colour I set it up so that the alpha has a default value if the user doesn't specify one.  That way I don't have to write two functions.  Here's an example:

    class func antiqueWhiteColor ( alpha: CGFloat = 1.0 ) -> UIColor { 
        return  UIColor.init ( red: 250.0/255.0, green: 235.0/255.0, blue: 215.0/255.0, alpha: alpha ) }

I do this instead of writing
    class func antiqueWhiteColor ( ) -> UIColor { 
        return  UIColor.antiqueWhiteColor (  alpha: 1.0 ) }

    class func antiqueWhiteColor ( alpha: CGFloat ) -> UIColor { 
        return  UIColor.init ( red: 250.0/255.0, green: 235.0/255.0, blue: 215.0/255.0, alpha: alpha ) }

**Comment by thii** [comment]
@NorthernRealities It seems like it's not possible in the init method.
